### ISSUE TITLE
Add error's parent names to the response

### ISSUE THREAD

**Issue by joelmukuthu** [One-com/node-express-errorhandler#3]
When you have an error that inherits other errors, it would be nice to include all the inherited error names in the response:
```javascript
const express = require('express');
const httpErrors = require('httperrors');

class DatabaseFetchError extends httpErrors.InternalServerError {}
class JobFetchError extends DatabaseFetchError {}

app.use(function (req, res, next) {
  next(new JobFetchError('foo'));
});
```
The response body could look like:
```javascript
{
  status: 500,
  error: 'JobFetchError'
  message: 'foo',
  extends: {
    JobFetchError: {
      extends: {
         DatabaseFetchError: {
           extends: 'InternalServerError'
         }
      }
    }
  }
}
```
Where the `extends` value could be a string, array (in future maybe) or an object (when the parent also inherits from another error).

**Comment by papandreou** [comment]
That's a bit verbose. Are you sure it would be that helpful? In your example, the only thing it adds is the fact that the encountered `JobFetchError` has `DatabaseFetchError` as an intermediate parent (we already know from the status code that it has `InternalServerError` at the root. And that could trivially be looked up in the code or docs).

Of course it's nice to have the information handy in the response body, especially if you have a bunch of `JobFetchError` classes sitting in different places in the error hierarchy.

An alternative could be adding the names of the error instance and the superclasses as properties with a value of `true`, like error instances created by `createError` ([httperrors](https://github.com/One-com/node-httperrors) and related modules):

``` js
{
  status: 500,
  error: 'JobFetchError'
  JobFetchError: true,
  DatabaseFetchError: true,
  InternalServerError: true,
  message: 'foo'
}
```

**Comment by joelmukuthu** [comment]
I was thinking of a format that could be used to reconstruct the error on the frontend (for tagging with failboat for instance). Since adding the errors as properties with `true` values doesn't guarantee that the property is a parent class-name, a less verbose alternative would be to list the parents in an ordered array, something like this:  

``` js
{
  status: 500,
  error: 'JobFetchError',
  extends: [
    'JobFetchError',
    'DatabaseFetchError',
    'InternalServerError',
  ],
  message: 'foo'
}
```

My previous suggestion makes it easy to add new properties to the parent error objects. This would also be possible with this suggestion though:

``` js
{
  status: 500,
  error: 'JobFetchError',
  extends: [
    'JobFetchError',
    { name: 'DatabaseFetchError', foo: 'bar' },
    'InternalServerError',
  ],
  message: 'foo'
}
```

**Comment by papandreou** [comment]
For a while I've also wanted to use the same error classes in the frontend and just "marshall" them over the wire somehow. That would do a lot for consistency in the webmail. I suppose that requires something like this.

**Comment by joelmukuthu** [comment]
A while back I tried to do this with errors created with https://github.com/One-com/node-createerror, but didn't quite manage. I had an easier time with ES6 error classes (using `prototype.constructor.name` through the prototype chain) so I ended up creating ES6 errors (e.g. https://github.com/joelmukuthu/knorm/blob/ee2ee50742557dba144074ceb3fab23bbfdb78a2/lib/createError.js). Do you know if it's possible to get the parent classes names for errors created with node-createerror?

**Comment by gustavnikolaj** [comment]
Closing.

**Comment by joelmukuthu** [comment]
> Closing.

As a "won't do"? :grinning:

**Comment by gustavnikolaj** [comment]
Hi @joelmukuthu! :-)

Yeah, I suppose so. I didn't think about it too much - I just noticed an old issue and thought I'd clean up a bit :-) We haven't needed it, but I suppose we can reopen if you feel strongly about it.

I see this particular module as a really really stable piece of code, but also a pretty stale one. I think there's a lot of things to be fixed (or just straight up removed) if we were to pick it up again. So the idea of adding new features feel quite foreign to me :-)

**Comment by joelmukuthu** [comment]
Hey! :)

I understand, I was just pestering you. I do agree that it could be improved, in particular IIRC it was quite hard (impossible?) to get the error names of the parent error classes. Anyway it's fine by me to close this :)
